import type { Metadata } from 'next';
import { Inter, Pixelify_Sans } from 'next/font/google';
import './globals.css';
import { ThemeProvider as NextThemesProvider } from 'next-themes';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });
const pixelifySans = Pixelify_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${pixelifySans.className} h-body`}>
        <NextThemesProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
          enableSystem>
          <Header />
          <main className="h-full px-6 pt-24">{children}</main>
        </NextThemesProvider>
      </body>
    </html>
  );
}
